force-app/main/default/objects/Ability__c/Ability__c.object-meta.xml
<CustomObject>
    <label>Ability</label>
    <nameField>
        <label>Ability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Abilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ability__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Abilities</relationshipLabel>
    <relationshipName>Abilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Move__c/Move__c.object-meta.xml
<CustomObject>
    <label>Move</label>
    <nameField>
        <label>Move Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Move__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Moves</relationshipLabel>
    <relationshipName>Moves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PokemonManager.cls
@RestResource(urlMapping='/Pokemon__c/*')
global with sharing class PokemonManager {
  @HttpGet
  global static Pokemon__c getPokemonById() {
    RestRequest request = RestContext.request;
    String pokemonId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);

    Pokemon__c result = [
      SELECT Name, (SELECT Name FROM Moves__r), (SELECT Name FROM Abilities__r)
      FROM Pokemon__c
      WHERE Id = :pokemonId
    ];
    
    return result;
  }

  @HttpPost
  global static Id createPokemon(String pokeName, List<String> moves, List<String> abilities) {
    Pokemon__c thisPokemon = new Pokemon__c(Name=pokeName);
    insert thisPokemon;

    if (moves.size() != 0) {
      List<Move__c> theseMoves = new Move__c[]{};

      for (String move : moves) {
        theseMoves.add(new Move__c(Name=move, Pokemon__c=thisPokemon.Id));
      }
      insert theseMoves;
    }

    if (abilities.size() != 0) {
      List<Ability__c> theseAbilities = new Ability__c[]{};

      for (String ability : abilities) {
        theseAbilities.add(new Ability__c(Name=ability, Pokemon__c=thisPokemon.Id));
      }
      insert theseAbilities;
    }

    return thisPokemon.Id;
  }
}